name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable

      - name: Build Target
        run: cargo build --target ${{ matrix.target }} --release --locked

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jet-cli-${{ matrix.target }}
          path: ./target/${{ matrix.target }}/jet

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./target

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/x86_64-apple-darwin/jet-cli-x86_64-apple-darwin
            ./target/aarch64-apple-darwin/jet-cli-aarch64-apple-darwin
            ./target/x86_64-unknown-linux-gnu/jet-cli-x86_64-unknown-linux-gnu
