name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Build Target
        run: cargo build --target ${{ matrix.target }} --release --locked

      - name: Create Tarball
        run: tar -czvf jet-cli-${{ matrix.target }}.tar.gz ./${{ matrix.target }}/release/jet
        working-directory: ./target

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jet-cli-${{ matrix.target }}.tar.gz
          path: ./target/jet-cli-${{ matrix.target }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./target

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/jet-cli-x86_64-apple-darwin.tar.gz
            ./target/jet-cli-aarch64-apple-darwin.tar.gz
            ./target/jet-cli-x86_64-unknown-linux-gnu.tar.gz
